### ISSUE TITLE
Make clear which non-recommendation can be normatively referenced

### ISSUE THREAD

**Issue by murata2makoto** [w3c/epub-3-wg-charter#1]
EPUB 3.2 relies on CSS Snapshot and some registries at IDPF.  CSS Snapshot is just a W3C Working Group Note.  IDPF registries do not have any official status in W3C.  Other standardization organizations disallow such normative references typically.

I am not saying that we should not make W3C Recs that rely on these normative references.  I just want to make clear what is allowed and what is not allowed.

**Comment by iherman** [comment]
What is the official situation, or a possible derogation, @swickr @plehegar ?

It is a separate question whether this should be part of the charter. My instinct says no. But it must be discussed and this is a good time for it...

**Comment by iherman** [comment]
@murata2makoto I believe the WG can (and maybe should?) take over the control and maintenance of the IDPF registries. Could you raise a separate issue on this? It would deserve a separate discussion and possible addition to the charter...

**Comment by swickr** [comment]
There is ample precedent in W3C Recommendation Track work for how normative references to CSS may be made.  The specific needs of a (future) EPUB 3 Recommendation will dictate what the (future) EPUB Working Group decides is the most appropriate set of CSS specifications to reference among the choices W3C has available.

The same applies to the IDPF registries; while they have no official status currently inside W3C (other than being among the assets that IDPF transfers), the Working Group has within its scope to propose what it believes their future status should be.  Thanks for splitting that conversation into #2.

**Comment by iherman** [comment]
@murata2makoto actually (as I was reminded related to another Working Group) the guiding document is [“Normative references”](https://www.w3.org/2013/09/normative-references). I believe that if follow the approach described there, we are covered on, say, the CSS reference.

If this is a satisfactory answer on the original question, could you close this issue?

**Comment by murata2makoto** [comment]
I agree that the W3C document “Normative references” is important.  But it does not mention CSS or W3C Note.  I thus think that my original question has not been answered yet.

It might make sense to defer the question to the upcoming WG.  But I do not want to easily close this issue without broader discussions.  I think that one reason of the failure of (P)WP was the charter created in a hurry.

**Comment by iherman** [comment]
> It might make sense to defer the question to the upcoming WG. But I do not want to easily close this issue without broader discussions. I think that one reason of the failure of (P)WP was the charter created in a hurry.

Any specific reason not to close this issue? Clearly, this is a central question for all WG work (and is for any Working Group, in fact) but I fail to see anything to be changed on the charter itself.

**Comment by murata2makoto** [comment]
What is the schedule for this draft charter?  The charter of the PWG was prepared in a hurry (for having a F2F) and was not extensively discussed in teleconferences.  New people did not join.  One guy left.  (P)WP failed.  I am not sure if we are not going to repeat the same mistake.  One could certainly argue against this charter completely (i.e., don't fix the spec when people know how to avoid pitfalls).

I guess that I should not use this issue for my concern.   Will close this issue in a few days.

**Comment by iherman** [comment]
@murata2makoto there is no fixed schedule. The charter draft includes start dates for the WG, but that is only a draft; those dates can, and should, be adjusted depending on the date when the charter is submitted for a formal approval to the Advisory Committee.

**Comment by murata2makoto** [comment]
@iherman Thank you.  Is an internal review by the PBG planned?  Will the draft charter be submitted to the AC without explicit support by PBG members?

**Comment by iherman** [comment]
I would leave the answer to the Steering Committee. But the PBG has been already asked, on several occasions, to comment on the charter in some way or other (and I thank you and others who have already done that, I think the charter has been improved in the past few days).

CC: @swickr @TzviyaSiegman.
