### ISSUE TITLE
List the SVG WG (and CG) in the Coordination section

### ISSUE THREAD

**Issue by frivoal** [w3c/epub-3-wg-charter#10]
The charter mentions SVG as a file format used in EPUB, and correctly links to its spec. This is good.

It also says:

>  Any properties or values that influence rendering inside viewports; these issues should be deferred to Working Groups defining rendering, like HTML, CSS, or SVG.

This is good too.

However, the SVG WG is not listed in the Coordination section. It should be, possibly alongside the SVG CG.

**Comment by dauwhe** [comment]
Fixed via #11
