### ISSUE TITLE
what refinements are planned for epub:type?

### ISSUE THREAD

**Issue by mattgarrish** [w3c/epub-3-wg-charter#12]
The planned improvements for the Content Documents includes this:

> Refinement for epub:type

It's not clear what this means, though. It could be interpreted, among other ways, as: 1) maintaining the vocabulary and adding/deprecating values; 2) adding a package document-like mechanism for associating semantics; 3) clarifying that ARIA role should be used for accessibility and they are not equivalent.

Some additional explanation here would really help, as at least one of the above thoughts frightens me.

**Comment by iherman** [comment]
> Some additional explanation here would really help, as at least one of the above thoughts frightens me.

Let me guess. No. 2?

My vote would go for 1) and also 3)

Plus... We have to clarify that if the content document is in HTML (without 'X') then `epub:type` cannot be used.

**Comment by mattgarrish** [comment]
> Let me guess. No. 2?

Bingo!

> My vote would go for 1) and also 3)

Technically only 3) would apply to content documents. The structural semantics vocabulary is a separate document and has had its own revision cycles. We generally always do some maintenance on it during a revision, but would it be helpful to list it as its own deliverable? I believe it's the only non-integrated vocabulary left, and someone needs to own it.

> Plus... We have to clarify that if the content document is in HTML (without 'X') then `epub:type` cannot be used.

Right, I'm assuming details like this are part of the whole issue of adding html as an option. That's what makes the separate mention of epub:type confusing.

**Comment by iherman** [comment]
> The structural semantics vocabulary is a separate document and has had its own revision cycles.

Oops, I did not realize this. 

> would it be helpful to list it as its own deliverable?

Absolutely. Otherwise it is a source of confusion. Is it a normative document, ie, yet another rec, or "just" a vocabulary note that needs some care? (I hope for the latter...)

**Comment by mattgarrish** [comment]
>  Is it a normative document, ie, yet another rec, or "just" a vocabulary note that needs some care? (I hope for the latter...)

Good question. It was never published as a recommended specification in IDPF so that we didn't have to do revisions to update it, but lived somewhere between a spec and an informational document.

It's normatively referenced as the [default vocabulary for epub:type](https://www.w3.org/publishing/epub3/epub-contentdocs.html#sec-contentdocs-default-vocab), so I don't know if publishing it as a note complicates anything process-wise?

Also, all the vocabularies we re-integrated during 3.2 are now technically normative appendices of the Packages spec. So this might be the only informative one.

If publishing as a note doesn't introduce any problems, though, I'm fine with going that route.

**Comment by iherman** [comment]
Alas! If it is a normative reference the the vocabulary cannot be a note. It must be a Rec, or part of a Rec... Otherwise we may get into trouble.

Must it be a separate document? Or can it be reasonably folded into another one?

**Comment by mattgarrish** [comment]
> Alas! If it is a normative reference the the vocabulary cannot be a note.

Right, and I wasn't even thinking about the nav doc definitions or its use in media overlays. It is tightly bound to the specs.

> Must it be a separate document? Or can it be reasonably folded into another one?

I guess that depends on whether we see it being revised more frequently than the core specs anymore. It used to get periodic updates as we developed edupub and the other satellite specs, but in the last few years we've hardly touched it. I tend to think we don't need to have it separate anymore.

I believe it would integrate easily enough as an appendix to the content documents specification since that's where the formal epub:type definition is. It's just unfortunately a rather large vocabulary that would have to be merged into a rather large specification.

**Comment by frivoal** [comment]
(EPUB noob here, but Process non-noob). Does this vocabulary *do* anything, or does it merely describe a bunch of values that exist and what they mean, but without any particular requirement on software to perform anything in particular when it encounters these values?

If it is that later (I think it is), I don't think it's that problematic to maintain this as a Note, at least until the Process CG manages to adopt a formal Process for maintaining registries at W3C (which might happen within the 2021 W3C Process revision cycle).

If this does include RFC2119 requirements on software to do particular things when faced with these particular values, then a Note would not be a great place to maintain them (nor would a registry, once those things exist), and if feels more like REC track material.

**Comment by iherman** [comment]
@frivoal yes, it is very much akin to a registry. And, actually, I may have to revise my opinion in https://github.com/w3c/epub-3-wg-charter/issues/12#issuecomment-612881024: after all, usage of registries via some publication means have been used before (and are being worked on in current WG-s like in the DID WG). If Process-2021 provides some general framework for registries (at last...) that makes it even cleaner and easier.

That being said, we may want to put some words in the charter about this.

**Comment by mattgarrish** [comment]
>  but without any particular requirement on software to perform anything in particular when it encounters these values

Strictly within content documents, no, there are no requirements.

But when you get to the navigation document the `toc` value is the key to identifying and processing the table of contents (the same is true of the `page-list` and `landmarks` values). It might be hard to classify those as not integral to processing.

Media overlays is a little murkier. The semantics are used to identify structures and allow behaviours like skippability and escapability but it's not required that the reading systems use the values.

**Comment by dauwhe** [comment]
> Refinement for epub:type

It was originally "Replacement for epub:type," but the text was changed in the draft Google Doc before being moved to GitHub. 

`epub:type` is perhaps the most problematic thing in EPUB content documents. How much time has been spent arguing about it, trying to explain it, trying to figure out how to use it? People think it's important for accessibility. It isn't. People think reading systems use this information. In most cases, they don't. It's a significant obstacle to allowing HTML in EPUB. 

Of course we can't get rid of it. But I have an incomplete wish list:

1. Make it clear that `epub:type` is not a substitute for ARIA roles, and that `epub:type` is not an accessibility feature. 
2. Encourage users who have workflow- or publisher-specific requirements to use existing HTML mechanisms like `@class` and `data-*`. 
3. Find ways to identify nav doc functions that would work in HTML.
4. Discourage reading systems from tying behavior to `epub:type`
5. How to deal with the desire for declarative ways of invoking complex features like pop-ups? I don't know. But I hope we can find ways consistent with the rest of the web platform.

**Comment by mattgarrish** [comment]
> It's a significant obstacle to allowing HTML in EPUB.

It doesn't have to be, though. As you say, we just make it a legacy xhtml-only EPUB feature and not bother with it anymore (with the recommendation to use ARIA for accessibility). We're not obligated to ensure that non-essential features work everywhere. Otherwise, what are you going to do about the ssml:* attributes?

> 3. Find ways to identify nav doc functions that would work in HTML.

This is one of the areas where pushes for HTML have fallen apart in the past. We can't reproduce all the semantics in ARIA, for example, and are unlikely to.

My advice would be to not to get into re-serializing the nav doc and just leave it as is. Whatever minimal benefit there might be in having an HTML equivalent is not worth losing HTML for content documents over. How often does it even get repurposed in the spine? (We can all just grow old hating it as an outmoded technology like the NCX. :)

But (seriously) I don't want to start a 100 response thread over this now. That time will come soon enough.

As I mentioned somewhere up above, I probably wouldn't even note this as a unique outcome of the revision, as it's dependent on HTML being accepted. It might be simpler to roll it up into the bullet about adding HTML:

> Allowing the HTML Serialization of HTML5, including whether and how to handle xml-specific technologies like `epub:type` and the `ssml:*` attributes

**Comment by iherman** [comment]
Yep, we should be careful about getting to a new permathread...

In #18 I have taken over what @mattgarrish proposed to nuance the `epub:type` issue.

I also believe that we may get by with the 'registry' approach for the `epub:type` vocabulary, although the requirement in TOC might be a problem. But we may argue, using the [normative references](https://www.w3.org/2013/09/normative-references) document that even that one may be o.k., if we somehow ensure the absolute stability of that term. However, we _may_ need to add the `epub:type` vocabulary as an explicit, albeit non-normative, deliverable of the WG...

#18 does not include anything on the latter. We may need a separate PR for this.
