### ISSUE TITLE
Be more explicit goals and motivations

### ISSUE THREAD

**Issue by frivoal** [w3c/epub-3-wg-charter#13]
The "Scope" and "Out of scope" sections seem reasonably clear about what the group can or cannot do, but they are less clear about the motivations for revising EPUB.

To some degree, in order to guide the decision making process as each case comes up, stating the motivations upfront may be useful.

More importantly, this should help organizations assess whether they have an interest in participating in the WG or not (and possibly, in whether they want to be W3C members for that purpose or not).

Getting EPUB to REC will attract participation from different people and organizations if the goal is primarily to get EPUB as it already exists to REC in order to increase interoperability through testing, refinements, and thanks to the discipline of the REC track, or if the goal is primarily to add new features, or if the goal is to improve the accessibility of existing features… As for new features, interest will also vary if those features are mainly targeted at making EPUB a better end-user format, or a better interchange format.

Maybe the goal is only one or some of those. Maybe it's a little bit of everything. Maybe it's not defined yet, and it will depend on who shows up. As it stands, it is somewhat hard to evaluate. There's more clarity about these in [the blog post](https://www.w3.org/blog/2020/03/listen-to-the-people-the-future-of-epub-and-new-directions-for-publishing-w3c/), but the charter, not the blog post, is what sets the frame for the working group, and is what the AC will be asked to vote on.

To some degree, the same is true for any charter, and we don't always insist on these motivations being listed up front, as long as the scope is clear. I think it is more relevant here than usual for several reasons:

* There is a lot of diversity in EPUB reading systems. That's a great thing in general, but only a small portion of that diversity is represented at W3C. If what we intend to do with EPUB-as-a-REC will need reading systems to implement new features, or to adjust the behavior of existing features to improve interoperability, the group will need a broad section of them well represented and engaged in order to be successful. That isn't necessarily true if the main focus is on features that are only relevant when EPUB is used as an interchange format, which would need a different set of participants.

* As I have argued in #8, changes in the EPUB ecosystem are more risky than on the core web platform:
    > Many parts of the web platform have a very powerful and forgiving compatibility model, with the behavior expected of the User Agent in the face of incorrect content being specified with as much detail as in the case of correct content. This makes evolution of the platform fairly safe, as the behavior of new documents in old user agents, or of new user agents when faced with old documents, even when the documents are non conforming, is predictable.
    > 
    > The EPUB family of specification has so far focused much more on the requirements on the document itself, and much less on the requirements on the software that is expected to process these documents. How such software reacts in the face of non conformant documents or documents with new features is less documented, less tested, less interoperable, and less understood.

    This doesn't mean we cannot change anything, but if the risk part of the risk/benefit trade-of is more pronounced, the benefit bar to met for a change or an addition to be worth doing is also higher. In order to judge that, knowing what the change is (which the WG will likely be good at) is insufficient, and knowing why the change or set of changes is being proposed is important as well.

* By and large, the publishing industry, which is the target of the EPUB family of specifications, operates on thinner margins and smaller budgets than the pure-software core of the Web industry. Also, a smaller percentage of its workforce is composed of technical/software people. In order to help make the case of why companies should put time and resources into participating, stating the motivations upfront is important.

* Various organizations have different priorities, and what is "obviously" important to some may not at all be to others, or could even be an anti-goal. This is true in any group, but the market for ebooks is highly fragmented. Different regions—and different verticals—have markedly different problems to solve and different priorities. Being upfront about what we're trying to accomplish will help organizations evaluate whether they want to support this group and how actively they should participate.

**Comment by iherman** [comment]
@frivoal though I understand your argumentation, we are probably between a rock and a hard place here. We have seen, in the past, several times remarks on charters being too detailed on such matter, requiring the charter to be much more succinct.

One idea may be as follows: as you say, the blog already gives some answers. We could add some more text summarizing what you describe above, add it to some public place and refer to both from the charter as a some an explainer. This approach worked in other charters before. W.t.y.t?

**Comment by frivoal** [comment]
I don't think it needs to be anywhere nearly as long as the blog. What I have in mind is more of a couple of sentences about what we're aiming to achieve, followed by a consolidation of the various points in "Technical improvement planned compared to the draft state" and of what is under "Other Deliverables", as well as a clarification as to whether this list is meant to be exhaustive of what is intended for this charter cycle, or whether it is an "at least these" list, or a "maybe some of these" list.

**Comment by iherman** [comment]
@frivoal I have lifted some text (only 1-2 sentences) from the blog into the draft, see PR #18. If you believe we need more than that, I think having a separate wiki page or something similar is probably the best solution...

**Comment by wareid** [comment]
I think Ivan's amendments in the PR address some of the clarification. I agree with him that this document cannot and should not be an exhaustive list of everything we might or might not look at in the EPUB documents.

**Comment by davidstroup** [comment]
Should the in scope document say something like "..includes but is not limited to"? 
For the out of scope section do we want to provide a footnote as to where the out of scope items will be discussed if known?

**Comment by iherman** [comment]
@davidstroup the PR #18, just merged, includes now just that!

**Comment by iherman** [comment]
Closing, per https://github.com/w3c/epub-3-wg-charter/pull/18#issuecomment-613818818
