### ISSUE TITLE
Surfacing "Technical improvement planned compared to the draft state" better

### ISSUE THREAD

**Issue by frivoal** [w3c/epub-3-wg-charter#14]
The Deliverable section includes a list of documents, expected deadlines, current drafts, and other information that is be mostly about the mechanics of publishing things.

For some of these documents, it also includes "Technical improvement planned compared to the draft state". This is important information, and its relatively easy to miss it where it currently is. Consolidating this in a goals section outside of the deliverable section would help explain the purpose and goals of the Working Group. This may offer part of the solution to #13 

Among these is "Allowing the HTML Serialization of HTML5". I think this is a major change to EPUB, that is well worth highlighting: both because the benefits of doing so are considerable, but so are the compatibility implications. This may end up being the single most impactful thing this WG does, or it may be the reason why some will oppose it's creation. This should be much earlier and much more prominent in the charter.

**Comment by iherman** [comment]
@frivoal I think #18 covers what you propose.
