### ISSUE TITLE
Distinguish EPUB 3.2 from EPUB 3.X

### ISSUE THREAD

**Issue by toshiakikoike** [w3c/epub-3-wg-charter#16]
In the scope it seems a little unclear that EPUB 3.2 and EPUB 3.X are different.
I hope it is clearly stated that EPUB 3.2 spec will be kept as is, and EPUB 3.X will be the following version.

**Comment by iherman** [comment]
@toshiakikoike thank you. I have added some text, making explicit what is 3.X and that 3.2 itself will not change, in the PR #18. Could you check whether this is o.k. with you?

**Comment by toshiakikoike** [comment]
@iherman Thank you. The texts are totally o.k .
