### ISSUE TITLE
Change "Allowing the HTML Serialization of HTML5" to "Considering allowing ~"

### ISSUE THREAD

**Issue by toshiakikoike** [w3c/epub-3-wg-charter#17]
About "Allowing the HTML Serialization of HTML5" stated below,
 &gt; 2.1 Normative Specifications
  &gt;EPUB Content Documents 3.X
    &gt;Technical improvement planned compared to the draft state:
      &gt; Improved Alignment with Web Platform:

I am afraid of "allowing" becoming a premise of the charter. HTML Serialization needs a lot of argument because it has a big impact on reading system and check tools.
So I propose changing the phrase to "Considering allowing the HTML Serialization of HTML5"

**Comment by iherman** [comment]
@toshiakikoike thank you. I have added some changes in the PR #18; could you check whether this is o.k. with you?

**Comment by toshiakikoike** [comment]
@iherman Thank you. The texts are totally o.k .
