### ISSUE TITLE
IDPF registries

### ISSUE THREAD

**Issue by murata2makoto** [w3c/epub-3-wg-charter#2]
EPUB 3.2 relies on some IDPF registries.  They are

- [Authority Registry] EPUB Subject Authorities Registry. URL: https://www.idpf.org/epub/registries/authorities/
- [RoleRegistry] EPUB Collection Roles Registry. URL: http://www.idpf.org/epub/registries/roles
- [TypesRegistry] EPUB Publication Types Registry. URL: http://www.idpf.org/epub/vocab/package/types
- [EPUB-SSV] EPUB Structural Semantics Vocabulary. IDPF. URL: http://www.idpf.org/epub/vocab/structure/

What should we do about them?

**Comment by iherman** [comment]
I believe, just like it is the case in several other WG-s, this Working Group should become officially the guardian of these repositories. The WG will have to develop the proper governance routes for them, but there are other examples we can follow.

I presume the IDPF URL-s should remain valid and redirected to the new incarnation of the registries (probably a github repo).

The question is whether this should be added to the charter.

**Comment by murata2makoto** [comment]
Could you provide examples of other registries owned by other W3C WGs?  I think that the charter should be clear about registries especially when the upcoming WG becomes responsible for them.

**Comment by iherman** [comment]
* https://www.w3.org/2011/rdfa-context/rdfa-1.1 is a sort of registry (not using the term).
* https://w3c.github.io/tt-profile-registry/ is in development
* https://github.com/w3c/did-core-registry is in development

There are probably more. There is also an active discussion on registries https://www.w3.org/wiki/Registries and there _may_ be some more explicit process steps in the future.

The details are not really of importance at this very moment; suffices to say that the EPUB 3 WG would certainly not be in an isolated position in handling such registries and, by the time this becomes relevant, we will have ways to do it.

>  I think that the charter should be clear about registries especially when the upcoming WG becomes responsible for them.

I tend to agree with you @murata2makoto, but we'd need more opinion before making a change on the text.

**Comment by swickr** [comment]
Thank you, @murata2makoto, for highlighting these registries.  As @iherman notes, it seems fairly clear to me for a future EPUB Working Group to be given responsibility for guardianship of these for the duration of its charter.  Any W3C Recommendation Track work that normatively cites those repositories should come with a clear expectation and documentation of their maintenance and change control.

I don't feel strongly that this does or does not need to be stated in the charter.  At present I feel it is a detail below the level of the charter.  We can leave it to the Working Group to propose in some detail how it believes those registries should be managed.  That proposal then becomes subject to wide review just as other parts of the normative specification(s).

**Comment by iherman** [comment]
The discussion on`epub:type` (see #12) have revealed that we may also need a registry for the values of `epub:type`. That one may be at the heart of some discussions in the WG (e.g., due to HTML usage) and, maybe for this reason, it may be worth adding a line to 2.2. (Other deliverables.) Something like

> - EPUB specific registries, such as values of `epub:type`, authoring registry, document type registries, etc.

**Comment by murata2makoto** [comment]
@iherman epub:type uses EPUB-SSV, which I mentioned already.

**Comment by iherman** [comment]
@murata2makoto 

>  epub:type uses EPUB-SSV, which I mentioned already.

you are right, but the point is that, per #12, that registry may be a matter of more discussions, hence I am of the opinion that adding them to the list of non-recommendation deliverables may be better.

@swickr wdyt?
