### ISSUE TITLE
No tests when we drop unused features

### ISSUE THREAD

**Issue by murata2makoto** [w3c/epub-3-wg-charter#20]
The last sentence in "Success Criteria" is "To promote interoperability, all changes made to specifications should have tests."  But when we drop features that have never been implemented, we do not need tests.

**Comment by iherman** [comment]
@murata2makoto I am not sure I understand this remark. You are of course right, but the success criteria is for the features that do become part of the standard. Ie, this sentence sounds all right to me.

**Comment by murata2makoto** [comment]
So, are you saying that features dropped from EPUB 3.X (X>2) do not require tests?

**Comment by iherman** [comment]
I presume this refers to the situation in #19.

I think the logical order in your question is misleading. The WG may decide not to _drop_ features, just mark them as non-standard (but nevertheless keep it in the specification as a non-standard feature). The "success criteria" refers to the features that do become (or not), at the end of the process, a recommended feature, and this is determined by the testing phase.

In practice, per process, the WG may process as follows. Exceptional features that the WG feels are in danger of _not_ getting two implementations, ie, that may not pass the success criteria, are officially marked as "At Risk" at the time of entering the Candidate Recommendation phase. Then the success criteria applies in the testing phase: if that particular feature does not pass the criteria then it becomes a non-standard features and marked it such. It does _**not**_ get "dropped" automatically, unless the WG decides to do so.

(I would think we all agree that this situation will affect a very minimal number of cases, if any.)

I would argue that the text in the current draft proposal is correct. It will be the job of the WG to decide how to proceed on specific cases when the time comes.

**Comment by murata2makoto** [comment]
@iherman You wrote: "if that particular feature does not pass the criteria then it becomes a non-standard features and marked it such".  But this is not documented in the W3C process document.  Is this your personal proposal?

**Comment by iherman** [comment]
Any WG has the right to include non-normative features in a Spec if it is properly marked (a  recent example is in the upcoming [JSON-LD 1.1 document](https://www.w3.org/TR/json-ld11/#the-rdf-compoundliteral-class-and-the-rdf-language-and-rdf-direction-properties)). The process talks about how a feature becomes _normative_ and the "at risk" mechanism _is_ [part of the process](https://www.w3.org/2019/Process-20190301/#candidate-rec). The WG has therefore the liberty to decide what happens to these "at risk" features in case they do not pass the criteria: being dropped or marked as non-normative. 

It is obviously not my role to say here what _should_ happen; this is the job of the WG. But, at this moment, we are simply discussing the charter.

Cc @swickr

**Comment by murata2makoto** [comment]
@iherman If I am not mistaken, the process document allows features at risk in CRs.  Not in RECs.

**Comment by iherman** [comment]
> @iherman If I am not mistaken, the process document allows features at risk in CRs. Not in RECs.

Of course. Once it is a Rec each feature is either normative or non-normative. The decision to get there for the type of features we are discussing may be done by following the 'at risk' procedure.

**Comment by wareid** [comment]
As Ivan said, it's far to early now to discuss what features will be normative or not, as it's not something we need to state in the charter.

Whatever happens, W3C has process for how to handle those features, and we'll follow it accordingly, if it is required.

**Comment by swickr** [comment]
@murata2makoto 
> 
> The last sentence in "Success Criteria" is "To promote interoperability, all changes made to specifications should have tests." But when we drop features that have never been implemented, we do not need tests.

All feature changes (even better, all features; not just those that have changed) should have tests; that is the way we'll know (during CR) whether the feature has interoperable implementations.  Tests can be classified as to whether a test failure is a conformance issue or not; that will also help the WG to decide what "conformance" means as they propose to advance the specification towards W3C Recommendation.

Features dropped might still be of interest to a future version of the spec.  Tests help confirm the WG's intent for that feature, whether it survives as normative, non-normative, or is deferred to a future version.

However, if a feature in a Working Draft was eventually determined to be a failed idea, any tests for that are likely not worth keeping.

**Comment by mattgarrish** [comment]
Is the question here about new features that we try to introduce into a 3.X that have never existed before or whether we have to include tests for features that exist in 3.2 right now but that we'll discover aren't supported and that we intend to deprecate?

I'm assuming the latter is being asked, and the statement is a bit at odds with that, no?

**Comment by mattgarrish** [comment]
Although it doesn't really matter. It only says there "should" be tests, so there's already enough leeway there for obvious non-testing scenarios.

**Comment by murata2makoto** [comment]
@mattgarrish I am talking about features in 3.2.  I don't know what is odd, but I agree that obvious non-testing scenarios are allowed by the use of "should".  @swickr  I also agree that we might want to create tests even for failed features.

**Comment by mattgarrish** [comment]
>  I don't know what is odd

Sorry, "at odds" just means to be in conflict. I agree there's no point developing tests for something we know we plan to deprecate, but I'm okay with the current wording allowing that.
