### ISSUE TITLE
Any properties or values that influence rendering inside viewports in 1.1

### ISSUE THREAD

**Issue by murata2makoto** [w3c/epub-3-wg-charter#21]
Since EPUB 3.2 already contains such properties or values, we need "new" or "addition".  Removal of unused such or adding a warning about the use of such are perfectly in the scope.

**Comment by mattgarrish** [comment]
> Since EPUB 3.2 already contains such properties or values, we need "new" or "addition".

If we don't want to get into adding more package metadata properties, we're certainly free to rule them out of scope for this revision.

But there is an assumption that all properties could be handled by other groups, and I'm not sure how likely that is. We could always leave some wiggle room by being less absolute:

"Any properties or values that influence rendering inside viewports<del>; these issues should</del> <ins>that can</ins> be deferred to Working Groups defining rendering, like HTML, CSS, or SVG."

**Comment by iherman** [comment]
Although a charter is not a recommendation, I believe the usage of 'should' is perfectly adequate in: 

> Any properties or values that influence rendering inside viewports; these issues _should_ be deferred to Working Groups defining rendering, like HTML, CSS, or SVG.

I.e., _unless there is a good reason to do it_, this WG is not in the business of adding new CSS attributes or HTML elements. Otherwise we would get into arguments about this WG attempting to "fork the Web".

I do believe the current text is adequate, and can cover the (exceptional) cases that might arise.

**Comment by mattgarrish** [comment]
> I.e., _unless there is a good reason to do it_, this WG is not in the business of adding new CSS attributes or HTML elements.

That's another problem with the bullet, as EPUB has gone in the direction of extending other technologies and also defined its own package rendering metadata. The bullet sounds like it rules out doing anything to package metadata, which includes epub-specific stuff like fixed layout metadata. I think we all agree the former needs to be out of scope, but the latter is a bit more complicated.

> I believe the usage of 'should' is perfectly adequate

It's not a normative/informative thing. The semi-colon splits the sentence into two separate clauses. The first says that all properties and values are out of scope. The second says requests should be deferred, but if not deferable the first requires we not look at them. I believe that's how @murata2makoto is reading it, too.

If we want to be completely clear, maybe we should separate the two:

- Any new elements, attributes, properties or values that would create a fork from open web technologies (e.g., HTML, CSS or SVG).
- Any new package document properties or values that influence rendering inside viewports that can be deferred to more appropriate working groups.

**Comment by iherman** [comment]
> Any new package document properties or values that influence rendering inside viewports that can be deferred to more appropriate working groups.

actually... I am not sure what this refers to. What is the meaning of 'viewports' in this context?

**Comment by dauwhe** [comment]
> actually... I am not sure what this refers to. What is the meaning of 'viewports' in this context?

I use viewport in the CSS sense--the area of the display where EPUB content is presented to the user. I had to use plural because of synthetic spreads, where the reading system needs to create two viewports side-by-side.

**Comment by dauwhe** [comment]
> * Any new elements, attributes, properties or values that would create a fork from open web technologies (e.g., HTML, CSS or SVG).
> 
> * Any new package document properties or values that influence rendering inside viewports that can be deferred to more appropriate working groups.

This works for me. But I very much hope that there are no new properties or values that cannot be deferred to other working groups. EPUB has gone quite a ways down the path of controlling rendering. We can't go backwards now, but we can at least stop increasing the distance between EPUB rendering and web rendering.

**Comment by mattgarrish** [comment]
> But I very much hope that there are no new properties or values that cannot be deferred to other working groups.

I share that sentiment, too!

I don't see anything in the tracker, and I'd hope we've had our fill of new rendering properties and values by now. The wording doesn't mean we have to accept anything, either, only that we don't bar any discussion by virtue of the scope.

**Comment by iherman** [comment]
Created a PR: https://github.com/w3c/epub-3-wg-charter/pull/22
