### ISSUE TITLE
Keeping backward compatibility and maintenance of EPUB business ecosystem; without any disruptions to be caused by the EPUB Recommendation Track process

### ISSUE THREAD

**Issue by dshioham** [w3c/epub-3-wg-charter#23]
In reference to the proposed charter above and intentions to moving forward with EPUB 3 for W3C Recommendation Track (“Rec Track”), we are writing this on behalf of the Japanese publishing industry community including publishers, eBook distributors, eBook reading system developers/providers, industry organizations, et al currently participating to the EPUB 3 based eBook business ecosystem to secure and confirm that the EPUB Working Group Charter is in compliance with the following:

Backward compatibility of the EPUB 3 specifications shall be maintained thoroughly.
The Rec Track process will not ill-effect the EPUB 3 specifications pertaining to the current EPUB business ecosystem from file creations, distribution and reading system.
The above basis shall be maintained even if the rec track process may seek the cases of utilizing a feature that was never implemented anywhere and adding any new features.In the event any doubt of occurrence of causing issues with the above basis, EPUB Work Group once established shall report details of such causes to all the members of Publishing@ W3C and seek consensus to proceed.

Further, we are in agreement with the Mr. Florian Rivoal’s already uploaded messages below to the EPUP Working Group proposed Charter and by quoting them, we intend to seek confirmation of the proposed Charter to conform with the quoted messages.

Junichi Yoshii (Kodansha)
Daihei Shiohama (Media Do)

(Mr. Florian Rivoal’s GitHub messages)
This doesn't mean we cannot change anything, but if the risk part of the risk/benefit trade-of is more pronounced, the benefit bar to met for a change or an addition to be worth doing is also higher. In order to judge that, knowing what the change is (which the WG will likely be good at) is insufficient, and knowing why the change or set of changes is being proposed is important as well.

By and large, the publishing industry, which is the target of the EPUB family of specifications, operates on thinner margins and smaller budgets than the pure-software core of the Web industry. Also, a smaller percentage of its workforce is composed of technical/software people. In order to help make the case of why companies should put time and resources into participating, stating the motivations upfront is important.

As an exception, features present in EPUB 3.2 must be kept when advancing to Proposed Recommendation even if there is no known implementation in a reading system, as long as documents using of these feature were accepted by epubcheck. Such features should (must?) be marked as deprecated (according to this definition), and related requirements on Reading Systems may be simplified, but documents using these features must not be made non-conformant to newer versions of the EPUB specification.

**Comment by iherman** [comment]
(For admin: the quote of @frivoal is in issue #8, that is where the specific discussions happen.)

**Comment by wareid** [comment]
I think we have strengthened the language around this in Ivan's latest revisions to scope, but if there is anything else we can change to further reassure anyone, please do provide suggestions!

**Comment by dauwhe** [comment]
> Backward compatibility of the EPUB 3 specifications shall be maintained thoroughly.

The charter states "Any EPUB 3.2 publication should be valid under any new version of EPUB published by this Working Group," which I think is an even stronger statement. I don't see how we can make that statement any stronger. 

> The Rec Track process will not ill-effect the EPUB 3 specifications pertaining to the current EPUB business ecosystem from file creations, distribution and reading system.

What is meant by "ill-effect"? Existing EPUB 3.2 files will be valid EPUB 3.X. It's possible that there will be new features in EPUB 3.X that are not in EPUB 3.2, which content authors, distributors, and reading systems can choose to support or not (just as most authors, distributors and reading systems do not support all features of EPUB 3.2). The advantage of the REC process is that all such features will have multiple independent implementations. 

> The above basis shall be maintained even if the rec track process may seek the cases of utilizing a feature that was never implemented anywhere and adding any new features.In the event any doubt of occurrence of causing issues with the above basis, EPUB Work Group once established shall report details of such causes to all the members of Publishing@ W3C and seek consensus to proceed.

I'm not sure I understand. Are you proposing that any consensus decision of the Working Group can be vetoed by the Publishing Business Group?

**Comment by murata2makoto** [comment]
@dauwhe 
>I'm not sure I understand. Are you proposing that any consensus decision of the Working Group can be vetoed by the Publishing Business Group?

In Japan, people follow the EBPAJ profile thus avoiding a lot of pitfalls of EPUB 3.  Features in this profile already have multiple independent implementations.  It is thus unclear what advantages the REC-track EPUB 3 can provide. 

> What is meant by "ill-effect"?

For example, non-XML syntax of HTML5 might cause such ill-effects, since some EPUB RSs in Japan are not based on browser engines.  Different RSs might parse the same HTML document differently.

**Comment by iherman** [comment]
> For example, non-XML syntax of HTML5 might cause such ill-effects, since some EPUB RSs in Japan are not based on browser engines. Different RSs might parse the same HTML document differently.

I am not sure I understand the example. If a RS is not based on an existing browser engine and, nevertheless,  _**if**_ that particular reading system decides to implement a non-XML syntax HTML5, then the EPUB 3.X (and, in this case, the HTML5's) test suite would play an essential role to implement that feature in an interoperable manner, i.e., to avoid the situation you are describing. In other words, different RSs might indeed parse the HTML document differently, but the work of the WG would aim at avoiding that to occur.

I must admit I consider this as a highly improbable and very hypothetical case: why would a RS implementer choose to do that, if the browser code is available? Also, the charter does not say the WG _MUST_ go down the road of non-XML HTML5 but only that the WG _MAY_ decide to do so.

**Comment by GeorgeKerscher** [comment]
Hello,

 

I too do not see this as an issue. Some dedicated devices without screens used by the blind may not use browser code for the implementation of their RS. They are responsible to address the audio presentation issues in those cases. This is normal implementation for them.

 

Best

George

**Comment by murata2makoto** [comment]
I remember that some commercial RSes were built without using browser engines.  I would like to ask other JP members about them.

It is true that, conformant implementations will interwork.  We only have to write good specs and build conformant implementations.  But why do we have to work hard and what advantages will we get?  My experiences with EPUB 3.1 and (P)WP make me skeptical.  As I wrote, in Japan, the EBPAJ profile already allows us to avoid non-interoperable features.

**Comment by wareid** [comment]
(Not to get completely sidetracked but) if EBPAJ is the guidance for Japanese publishers instead of the specification documents, what are we missing in the docs that would bridge that gap? What issues does EBPAJ address the docs don't, especially given the revisions in EPUB 3.2? That seems to be a more pressing matter than whether RSs do or do not use browser engines (something that we cannot control, nor should appear in this charter!).

**Comment by mattgarrish** [comment]
Could this be solved by adding a bullet like the following to the out of scope section?

- Removal of existing EPUB-defined features. Existing features will only be deprecated per existing practice.

It means align-x-center remains, for example, but it would be reduced to a deprecation statement pointing back to 3.2.

We need to be careful when we say that no features will be removed, as we don't control the technologies used to create the content.

**Comment by iherman** [comment]
Is there any feature that has _no_ implementations? Or features that, although implemented, but absolutely _nobody_ uses? Because these would be valid reasons for removal as part of a cleanup action, but this clause would forbid that...

This may be fine but we should do that with eyes wide open. Otherwise I agree that this may be the least disruptive way to handle this problem.

<sub>[View in Slack](https://iherman.slack.com/archives/C011FD3ST52/p1587815629000100)</sub>

**Comment by mattgarrish** [comment]
> Because these would be valid reasons for removal as part of a cleanup action, but this clause would forbid that...

But this is where we've gotten hung up in the past. Determining what is supported where isn't as easy as it is with browsers. And we have people who have used a feature even though it isn't supported and don't want their publications to become invalid.

Some "features" are like metadata, so SSML, pronunciation lexicons, package metadata, etc. don't have to work to be usable without negative effects.

**Comment by iherman** [comment]
Thinking about it further... maybe we are fine. This charter isn't for eternity... a charter may come for a subsequent working group which would stipulate that deprecated features may be removed. We set ourselves limits for these two years. 

+1 for me, thus!

**Comment by iherman** [comment]
(Editorial) Maybe 

> features defined by EPUB 3.2

sounds better?

**Comment by mattgarrish** [comment]
> a charter may come for a subsequent working group which would stipulate that deprecated features may be removed

Right, I suspect we'll need an epub 4 to set that break point, but eventually 3.1 will be recognized for being ahead of its time.

After spending the last 5 years on whether we can throw things out, though, now is probably not the time to rehash the arguments again. Whatever our feelings on thrown out/deprecated, the exercise of clarifying the dead and dying features did help bring clarity about what isn't going to be viable going forward. Both approaches do that.

**Comment by murata2makoto** [comment]
@mattgarrish Thanks, Matt.  Yes, this bullet is great!

**Comment by iherman** [comment]
Created PR #29

**Comment by dauwhe** [comment]
@dshioham We have made many changes to the charter since this issue was opened, including success criteria that explicitly mention maintaining the global ecosystem. Are you happy with the changes? Is it OK to close the issue now?

**Comment by iherman** [comment]
@dshioham, I think all the issues/questions have been discussed, and the charter proposal reflects consensus. In order to send the charter proposal to the AC vote (possibly next week), I would like to close this issue by this week end. Is that o.k.?
