### ISSUE TITLE
Foreign resources, CORS, and alignment with Open Web technologies

### ISSUE THREAD

**Issue by mteixeira-wwn** [w3c/epub-3-wg-charter#26]
We've defined the following as in-scope for the WG—

> Clarifications to the current use of open Web technologies, such as supported JavaScript APIs and CSS modules. 

And under **Other Deliverables** we list—

> Relationship of CORS requirement and EPUB content.

With the above in mind, to what extent are we considering work on external/remote resources? Issues around `iframe` elements in particular have come up in [EPUBCheck as well](https://github.com/w3c/epubcheck/issues/852).

The inclusion of foreign resources carries significant value for educational publishing. But we now know from market research, too, that some reading systems embed dynamic content (advertisements) in iframes, though post-ingestion (thus post-validation, meaning they can do whatever they want).

Currently, the lack of clarity and kludgy workarounds (as demonstrated in the EPUBCheck issue above) are a significant limitation. It is unclear how this issue fits in the roadmap for EPUB 3.X. At the very least, some additional clarity on bounds, security, etc., would be helpful, and might warrant a note under the first point in the charter.

**Comment by iherman** [comment]
@mteixeira-wwn the "other deliverables" says:

> Other non-normative documents _may_ be created such as:

(emphasis is mine). Which means we could add this line into the list without any problems, it does not mean an obligation for the WG to really do it, but it is good to show that this is an issue we care about.

Can you propose a text to be added there?

**Comment by dauwhe** [comment]
I think this is an important issue. In the past, EPUB has been described as a website in a box, with everything needed to render the EPUB right there. But we've been slowly creating exceptions to that principle. So where do we draw the line? How do we balance the obvious needs of education with the potential risk of bad user experiences in reading systems that can't handle external resources?

**Comment by iherman** [comment]
@dauwhe @mteixeira-wwn can you offer a suitable text in the charter? Or should we leave it open in the charter itself and leave that to the CG (the list of open issues that may come into the WG for discussion is pretty much open ended). 

Personally, I would opt for the latter, and leave it to the WG and CG chairs to look into this when the time comes.

(If you agree with the latter, we should close this issue, imho. We could also add a separate label of the sort 'Leave it for the WG', so that we would not forget...)

**Comment by mteixeira-wwn** [comment]
I'm very late in replying to this, but there's a minimum viable product approach to this topic that doesn't open a can of worms. We know that remote resources in EPUB is a reality. Educational publishers use them, whether or not it's valid to do so, and retailers do the same by embedding advertisements. Norton in particular is looking into shifting the internal representation of our higher ed ebooks from OPF to Pub Manifest particularly because it provides more guidance and prescriptions around this issue, which also helps in designing features like offline access.

My suggestion would be perhaps to simply revise this point—

> Relationship of CORS requirement and EPUB content.

To this—

> Relationship of CORS requirements, externally hosted resources, and EPUB content.

To the extent that this is a validation issue, I believe it can be discussed both in EPUBCheck and EPUB 3.X contexts. For anything beyond simply allowing the presence of remote resources, such as analytics, eventing, data exchange, etc., I think those are entirely out of scope for the WG and good candidates for CG examination.

**Comment by iherman** [comment]
I am o.k. with this, but @dauwhe @wareid and @shiestyle should definitely chime in...

**Comment by shiestyle** [comment]
I also think that discussing remote resources for future EPUB is important.
