### ISSUE TITLE
Largely thumbs up

### ISSUE THREAD

**Issue by GarthConboy** [w3c/epub-3-wg-charter#27]
This seems largely reasonable (and good) to us.

The only concerns raised were around all of the deliverables coming at basically the time of Charter expiration and and all of the deliverables coming at the same time.

Perhaps extend the initial Charter length somewhat?

I don't really see a great way of splitting (over time) the deliverables, but perhaps Media Overlay and A11Y could follow the initial four?  But, I could see, and appreciate, push-back there.

**Comment by dauwhe** [comment]
This issue also came up in #15. 

Are charters always two years? Are there risks associated with asking for more?

**Comment by iherman** [comment]
> Are charters always two years? Are there risks associated with asking for more?

In general, and extension request is never automatically granted; the group has to show that real advances have been made and there is a reasonable perspective of properly closing the work if the extension is granted. This, by itself, may not be a bad thing, because it holds the WG at bay.

Asking for 3 years upfront may be an alternative, too, I do not know whether it is done these days.

@swickr ?

**Comment by mattgarrish** [comment]
> I don't really see a great way of splitting (over time) the deliverables, but perhaps Media Overlay and A11Y could follow the initial four?

Not sure that would work.

Media Overlays is normatively referenced from the main spec and packages, so we couldn't move those without it.

The accessibility spec probably can move faster than the core specs, and it needs updating to match the coming ISO version. I'm not even sure how testing fits in with it, if at all, as it's guidance on authoring and doesn't change reading systems.

**Comment by iherman** [comment]
Yep. I am more inclined to follow @dauwhe's proposed change in https://github.com/w3c/epub-3-wg-charter/issues/15#issuecomment-619209600 if that works.

**Comment by GarthConboy** [comment]
Yes, that would likely help.

Best,
   Garth

**Comment by iherman** [comment]
Addressed in #33 by extending the charter until the end of the year, and adding some caveats on the timeline section.

**Comment by iherman** [comment]
@garth, we have extended the charter to 2.5 years. Is it o.k.? Is it o.k. to close this one?

**Comment by GarthConboy** [comment]
Great -- I think this and perhaps a little (optional) scope reduction is very helpful.  Thank you.  Closing.

These were the only non-"thumbs up" comments from Google, so I guess we're fully thumbs up now!  :-)
