### ISSUE TITLE
EPUB Accessibility Techniques

### ISSUE THREAD

**Issue by murata2makoto** [w3c/epub-3-wg-charter#28]
The draft charter mentions this IDPF document, but does not explain it.  At least, a link to that document is required.

**Comment by iherman** [comment]
You are right. I have added a reference in https://github.com/w3c/epub-3-wg-charter/commit/72ccb253cfa470e9c5ff4753911ea9fca93bce4d

Closing the issue.

<sub>[View in Slack](https://iherman.slack.com/archives/C011FD3ST52/p1587779960000100)</sub>
