### ISSUE TITLE
Market impact by allowing the HTML Serialization of HTML5

### ISSUE THREAD

**Issue by shiestyle** [w3c/epub-3-wg-charter#30]
First of all, I think the future EPUB 3.X should be updated and catch up the latest Open Web Platform technologies such as HTML5 and JSON.

However, maybe especially in Japan, changing fundamental specification will bring big impact to the market although adding new features will be fine.

Japanese text layout is complicated and so we have house rules (restricting features or expressions to be used in EPUB files) for generating EPUB files in order to keep display quality for several Reading Systems. After changing XHTML5 to HTML5, content providers will generate incorrect files easily (Web browsers may try to display in their own way) but it will be harder and harder to display the content correctly for Reading Systems.

Customers will expect that paid contents like eBook will be displayed correctly rather than free web contents thus it is also important to keep quality of displaying contents for the eBook market. It may not be the technical issue but we should consider some technical countermeasures to avoid such situation.

So I hope that careful discussion will be promised in this WG about allowing the HTML Serialization of HTML5.

**Comment by iherman** [comment]
@ShinyaTakami, I would need some clarification...

The current charter proposal says:

> Integration of new Open Web Platform technologies for enhanced digital publishing experiences; these may include, but not limited to:
> - new media types, such as OPUS, BPG, or WebP;
> - allowing the HTML Serialization of HTML5, including whether and how to handle xml-specific technologies like epub:type and the ssml:* attributes;
> The effects of such new technical features on deployed systems and checking tools must be carefully analyzed. In case of doubt, such features should not be added to EPUB 3.X.

The last sentence aimed at a safeguard that includes the possible HTML serialization. Can you propose a text to replace or extend this sentence in case you feel that is not enough?

**Comment by shiestyle** [comment]
Thanks @iherman.

How about changing the sentence like below?

_"The effects of such new technical features on deployed systems and checking tools and the risk of additional cost for adoption must be carefully analyzed."_

**Comment by iherman** [comment]
@ShinyaTakami I am fine with such a change; I will prepare a PR later today. 

<sub>[View in Slack](https://iherman.slack.com/archives/C011FD3ST52/p1587981239000300)</sub>

**Comment by shiestyle** [comment]
@iherman Thanks, again.
