### ISSUE TITLE
Proposing new EPUB "version" if compatibility will not be kept

### ISSUE THREAD

**Issue by shiestyle** [w3c/epub-3-wg-charter#31]
This Working Group will use version=”3.0” for the package file but I think version="3.0" should not be used if the compatibility with existing versions of EPUB 3 will not be maintained during REC process.

When an incompatible version of EPUB will be born, EPUBCheck will follow the latest version of EPUB and the check method will be updated for the incompatible specification. The new EPUBCheck may output errors or warnings to existing EPUB files. The different version will be one of the options to distinguish different specs for EPUBCheck and Reading Systems.

So I propose to add some comment to the charter about the incompatible version that may be generated by this WG. Otherwise, the compatibility (avoiding unexpected cost for re-generating files) should be maintained if using version="3.0".

**Comment by iherman** [comment]
@ShinyaTakami thanks. I do have a question though. The charter talks about _backward compatibility_. I.e., any EPUB 3.2 content should remain valid under EPUB 3.X. What type of "incompatible version" do you refer to here in your comment?

**Comment by shiestyle** [comment]
I know this working group will try to maintain the compatibility with EPUB 3.2 or current market but  I'm not sure it's possible or not. If maintaining the compatibility will be prioritized than making REC version, it's no problem but if not so, we should consider the incompatible version may be born by this working group.

If someone can guarantee the compatibility, "should" can be changed to "MUST", but I think it's not good idea.

**Comment by iherman** [comment]
> I know this working group will try to maintain the compatibility with EPUB 3.2 or current market but I'm not sure it's possible or not. If maintaining the compatibility will be prioritized than making REC version, it's no problem but if not so, we should consider the incompatible version may be born by this working group.

@ShinyaTakami thanks for the clarification. However, this charter is for the lifetime of _this_ working group. _If_, during the lifetime of the group, such situation arises then we do have two options:

1. the group goes back to the community and the W3C members exposing the situation and seeks an approval for an explicit _rechartering_ of the group; or
2. the group postpones this issue and goes through a new chartering round (including those features) once a new group this one expires

It entirely under the control of the group which of the two options are chosen. But, also in view of the concerns of some publishers expressed in a number of other issues (see, e.g., #23, #8) I personally think it is better to keep with the strong backward compatibility requirement at this moment.  

@dauwhe @wareid

**Comment by shiestyle** [comment]
Thanks @iherman.

I understand two options and I think both of them will be fine.

**Comment by iherman** [comment]
Thanks @ShinyaTakami. Is it o.k. to close this issue now? I do not think that there is anything to add/modify on the charter; those options are part of the W3C Process.

**Comment by shiestyle** [comment]
OK, thanks!
