### ISSUE TITLE
Confusing future-looking statement

### ISSUE THREAD

**Issue by mattgarrish** [w3c/epub-3-wg-charter#35]
I had to read this a few times to wrap my head around it:

> EPUB 3.X will endeavor to remain compatible with existing content. Any EPUB 3.2 publication should be valid under any new version of EPUB published by this Working Group, unless it relies on features that are subject to errata on EPUB 3.2.

The use of "any new version" goes beyond 3.X and this charter, no? I don't think there is any errata against 3.2, but it made it sound like someone could issue errata on 3.2 in the future even though it's been replaced by a newer version.

I think the answer is as simple as switching "any new version" with "the new version", but am open to still misunderstanding the intention here.

**Comment by iherman** [comment]
Well... I guess that leaves the door open to publish epub 3.2.1 and then epub 3.3 for whatever reasons. It is highly unlikely, but we shouldn't tie our hands.

**Comment by mattgarrish** [comment]
> It is highly unlikely, but we shouldn't tie our hands.

But this is where it gets confusing, as nowhere else does it say anything about producing multiple versions. There's only this:

> The Working Group will produce a new version of EPUB 3, codenamed “EPUB 3.X” for the purposes of this charter

Shouldn't that say "at least one new version"? I was assuming we would recharter if we did another version.

But, in any case, once we start talking more than one revision into the future, errata on 3.2 goes stale after the first 3.x. Errata on 3.x could invalidate 3.2.

If the goal is to be flexible, though, maybe remove all specifics:

"Any EPUB 3 publication should be valid under any new version of EPUB 3 published by this Working Group, unless it relies on features that are subject to errata."

**Comment by iherman** [comment]
I can go with that, but I would wait for the others before changing the text. This is a very sensitive sentence:-)

@dauwhe ? @wareid ?


<sub>[View in Slack](https://iherman.slack.com/archives/C011FD3ST52/p1588163699000500)</sub>

**Comment by dauwhe** [comment]
This whole statement worries me. An extreme example: we publish errata on 3.2 that invalidates every existing EPUB 3.0, 3.0.1, and 3.2. That would not, to put it mildly, be good! 

I think the goal is relatively clear: Any existing EPUB which is valid to EPUB 3.2 remains valid to EPUB 3.X, where EPUB 3.X is the product of this working group and its charter. What about

> EPUB 3.X will endeavor to remain compatible with existing content. Any EPUB 3.2 publication should be valid under any new version of EPUB 3 published by this Working Group under this charter. 

I'm a little wary of a general statement about EPUB 3, as I am not confident that there may be edge cases of 3.0 or 3.0.1 which might not be valid 3.2?

**Comment by iherman** [comment]
I will do a PR with the latest text and ask for explicit review request from others.

**Comment by mattgarrish** [comment]
> This whole statement worries me.

Yup, I share the feeling. I'm not just nitpicking this to be a PITA.

The validity question is a loaded one, especially when new warnings are valid but not always thought of that way. I don't think there are any surprises lurking around in the earlier specs (modulo 3.1) as we were pretty good about only expanding validity not restricting it. That's why the fxl properties don't require anything more to be supported than what a reading system already does, for example.

Where the surprises can come from is the underlying technologies. We can never say for sure that HTML won't push out some feature that makes existing content invalid (the table border attribute, for example, isn't technically allowed now that we use the whatwg spec, but gets a wash in validation).

There should be some leeway for major flaws, though. If we discover a major security flaw in epub at some point, for example, invalidating all earlier content isn't a bad thing and should result in errata in advance of a new spec.

> What about
> 
> > EPUB 3.X will endeavor to remain compatible with existing content. Any EPUB 3.2 publication should be valid under any new version of EPUB 3 published by this Working Group under this charter.

This works for me, too, as it removes the confusion about what version we're talking about and what errata. There's enough room for serious flaws to be addressed.
