### ISSUE TITLE
Reference to the survey we've made

### ISSUE THREAD

**Issue by cmussi** [w3c/epub-3-wg-charter#45]
I think that in the Charter we should to refer to the survey's requests, because there are several points to which you should give a structured answer, for example: linear=no, dual languages, etc..

**Comment by iherman** [comment]
I agree we should have a reference, although I do not think we should get into too much details. This has not been done so far because the survey results, mainly their overview, have not been published yet. @wareid @mteixeira-wwn when do you think this will happen?

**Comment by wareid** [comment]
I'll look into it today, I was waiting on feedback from the SC.

**Comment by dauwhe** [comment]
Closing as the reference to the survey was added
