### ISSUE TITLE
Add coordination with the APA WG

### ISSUE THREAD

**Issue by brewerj** [w3c/epub-3-wg-charter#52]
Please add the Accessible Platform Architectures (APA WG) to the W3C groups listed. (The Accessibility Guidelines Working Group is listed because of potential uptake of EPUB Accessibility; the ARIA WG is listed because of potential use of ARIA in EPUB. But APA WG is the W3C WG usually used for horizontal reviews of accessibility architecture; for instance, for publishing, possible use of accessible notation for knowledge domains in science and math publications.) Link is http://www.w3.org/WAI/APA/

Suggested text: 

Accessible Platform Architectures Working Group
The APA WG provides horizontal review of potential accessibility issues in the architecture, as well as accessibility impact of a specification.

**Comment by iherman** [comment]
@brewerj per the charter template, the groups listed under 4.1 are labelled as 'additional' groups, beyond those that are responsible for horizontal reviews. The HR-s are as a general statement in the introductory paragraph.

I do not mind adding the APA, but then I should also add the other relevant groups like i18n, privacy, security, and maybe the TAG, which makes the list pretty long. AFAIK, the current setup reflects the current usage in charters.

@wseltzer what say you?

**Comment by wseltzer** [comment]
From my perspective, no need to add groups for horizontal review purposes. If @brewerj is suggesting APA coordination beyond review, fine to add.

**Comment by iherman** [comment]
> If @brewerj is suggesting APA coordination beyond review, fine to add.

my reading of the proposed text is that it is for horizontal review.

**Comment by brewerj** [comment]
Amended proposal with specificity so that pre-coordination on this item is not overlooked: 

Accessible Platform Architectures Working Group
The APA WG provides horizontal review of potential accessibility issues in the architecture, including knowledge domains for STEM accessibility; as well as accessibility impact of a specification.

**Comment by iherman** [comment]
I am not sure I understand, @brewerj. Why would we single out a specific area of publishing (I presume you use the term STEM in this respect) and not others? Why is that different from the usual horizontal review?

**Comment by brewerj** [comment]
@iherman The effect of the minimalist "be sure to check with your horizontals" seems to be focused on post-development checks, rather than pro-active coordination. I do not believe that adequately serves the purpose of driving pro-active coordination on specific areas of work that may benefit from discussion during development, rather than after the fact when anything they try to develop together would slow the spec down. So yes it is an effort to call out a specific area of work.

**Comment by iherman** [comment]
I think what I wrote in https://github.com/w3c/epub-3-wg-charter/issues/52#issuecomment-641195446 pretty much stands: 

> I do not mind adding the APA, but then I should also add the other relevant groups like i18n, privacy, security, and maybe the TAG, which makes the list pretty long.

What you say is not special to a11y, the same could be said on i18n and the others. Per the whole process of horizontal reviews, the way I understand it, Working Groups are increasingly asked to keep in contact with the various horizontal review groups as early in the process as possible and reasonable. We already have a very long list of liaison groups in the charter (much longer than usual), and I am wary of adding 4-5 more.

**Comment by brewerj** [comment]
@iherman Philippe will update you on this, but I think it is inaccurate to think that the extent of intersection between a given Web for All "horizontal" is the equivalent for every charter, and therefore must be listed in an exactly parallel way. 
In the case of EPUB, there's a strong history of commitment to accessibility work, and consequently several areas of intersection. The accessibility effort itself is complex, and getting accessibility to work well in digital publishing consequently involves cross-review and/or joint development with several different WGs, in this case AGWG, ARIA, and also APA. 
This discussion is further convincing me that identifying and clarifying these separate coordination points may be particularly useful for this charter.

**Comment by dauwhe** [comment]
Fixed via #57
