### ISSUE TITLE
Publishing Community group Participation

### ISSUE THREAD

**Issue by GeorgeKerscher** [w3c/epub-3-wg-charter#7]
In section 4.1, the W3C group s are listed.

The link to Publishing Community group is nested in the description of the Publishing Business Group. I think this should be its own group for coordination.

I believe that the Working Group should actively engage with the Publishing Community Group.  It is from the PCG that we will be able to gain informed feedback and ideas on how to proceed. I believe we will find that there is as much expertise in the PCG as there will be in the EPUB WG. By making an extraordinary effort to engage the PCG, I believe we will be doing a better job of maintaining a solid relationship of the publishing community worldwide, not just inside the W3C.

**Comment by iherman** [comment]
@GeorgeKerscher this bug has been taken care of in #6. Could you check there whether the text is now o.k.?

**Comment by GeorgeKerscher** [comment]
I think this language is OK, but I want to make sure the PCG is on top of what the WG is proposing.

 

Best

George

**Comment by iherman** [comment]
@GeorgeKerscher, I have pinged @mteixeira-wwn in https://github.com/w3c/epub-3-wg-charter/pull/6#issuecomment-612927451. I will close this issue and discuss possible changes in #6, in conjunction with the PR.
