### ISSUE TITLE
Strengthen compatibility requirements, involve epubcheck

### ISSUE THREAD

**Issue by frivoal** [w3c/epub-3-wg-charter#8]
The scope section states that compatibility is an important goal, and that is good. But I think it needs to be more explicit and to go further.

Many parts of the web platform have a very powerful and forgiving compatibility model, with the behavior expected of the User Agent in the face of incorrect content being specified with as much detail as in the case of correct content. This makes evolution of the platform fairly safe, as the behavior of new documents in old user agents, or of new user agents when faced with old documents, even when the documents are non conforming, is predictable.

The EPUB family of specification has so far focused much more on the requirements on the document itself, and much less on the requirements on the software that is expected to process these documents. How such software reacts in the face of non conformant documents or documents with new features is less documented, less tested, less interoperable, and less understood.

It also means that introducing new features that would have been non conformant in previous version is risky. Maybe it will be safely ignored by existing readers and other processing software, but maybe not. Similarly, tightening and clarifying definitions of existing features might help with compatibility, but it might also end up disallowing existing practices used in actual documents (intentionally or accidentally) and accepted by existing software.

This situation in general makes it very difficult to reason about what is or isn't a safe change.

Some large deployments of EPUB also involve business models with fairly low margins, and therefore have very limited resources to deal with any perturbation introduced by incompatible changes, making the problem all the more concerning.

Fortunately, the publishing community has by and large been very strict about testing the content itself, through widespread use of epubcheck.

I think the charter should recognize that, and enshrine some compatibility principles that involve epubcheck, for the sake of protecting existing deployments. Maybe something like:

> If the EPUB 3.2 specification and epubcheck are found to disagree about something (i.e. the specification allows something that epubcheck rejects, or the publication bans something that epubcheck accepts), it is more likely that existing content and reading systems conform to epubcheck than to the specification, and therefore the new specification should be changed to match epubcheck, rather than the other way around.

The first part ("the specification allows something but epubcheck rejects it") because it is not well known how reading systems will cope with "valid" content that had been rejected so far and therefore not used, and the second one ("the publication bans something but epubcheck accepts it") because we should not cause problems for existing deployed content. It's probably OK to keep this as a "should" rather than elevate that to a "must", as there may be case where the change would be highly desirable and a thorough investigation can show that there exists no content/reader that would break as a result of that change, but the default position should be to side with existing deployments, and great care should be taken if we ever want to go against this.

Even this does not eliminate risks to existing ecosystems, as it is possible that, as a result of new features or of improved definitions making existing features newly useful, new documents that would be accepted by the current version of epubcheck start being produced, while triggering bugs in existing reading systems or other processing that had not encountered such documents before. Nonetheless, sticking to what epubcheck currently sees as valid is likely to significantly reduce the risk of breakage.

Relatedly, the "Success Criteria" section states that:

> In order to advance to Proposed Recommendation, each specification is expected to have at least two independent implementations of each of feature defined in the specification. 

That is usual for REC track documents, but for existing features that epubcheck has been accepting, we should be very wary of removing them from the specification, even if they had no implementation in any reading system, or only one. This removal may cause an updated version of epubcheck to start rejecting documents it previously accepted, and this could be disruptive of existing deployments. There may well be documents out there which attempt to use, without success, features that no reading system has implemented, and yet have been successfully sold/distributed (with that feature not accomplishing its intended goal, but the rest of the document remaining usable). Such content should not find itself locked out of upgraded toolchains.

Maybe we can include an additional statement along the lines of:
> As an exception, features present in EPUB 3.2 must be kept when advancing to Proposed Recommendation even if there is no known implementation in a reading system, as long as documents using of these feature were accepted by epubcheck. Such features should (must?) be marked as deprecated (according to [this definition](https://www.w3.org/publishing/epub32/epub-spec.html#deprecated)), and related requirements on Reading Systems may be simplified, but documents using these features must not be made non-conformant to newer versions of the EPUB specification.

----

If we adopt this kind of wording, we should probably be specific about which version of epubcheck we're talking about. Probably the latest in the 4.2.x series (4.2.2), although maybe the 4.1.x series is still more commonly deployed.

**Comment by murata2makoto** [comment]
In general, I love backwards compatibility with existing EPUB publications.  But I have thought that some features in EPUB 3.2 has never been used.   For example, has [rendition: align-x-center](https://www.w3.org/publishing/epub3/epub-packages.html#align-x-center) been ever used?  Even if epubcheck does not complain about this, I am happy to drop this feature.

**Comment by wareid** [comment]
I am reluctant to tie EPUBCheck and EPUB3.X too tightly together since they're independent of each other. EPUBCheck validates EPUBs based on the requirements laid out in the specification, but also does more than that (and has more planned in the future). 

I'd love an example of something where EPUBCheck and the spec disagree (except the major known one regarding spine order please). I don't think there are many examples. If anything, there is likely larger gaps in what EPUBCheck considers valid based on the specification and what reading systems have problems with, but that is something we aim to address in reading system conformance. 

We discussed including EPUBCheck in the charter, but felt it would be inappropriate considering it is an independent entity.

**Comment by TzviyaSiegman** [comment]
@wareid said what I was going to say. We intentionally did not tie EPUBCheck to the charter because it functions independently. The https://github.com/w3c/epubcheck community has been extremely responsive to concerns about compatibility with real-world workflows. I think we can close this issue as  I believe it is not relevant to the charter but to EPUBCheck.

**Comment by frivoal** [comment]
I agree that epubcheck being an external entity makes this a little awkward. Also that they have been very responsive and cooperative, so I am not worried about them as such.

In practice, epubcheck has defined what EPUB is more than the spec has, because that is what documents have been validated against. Not that they are necessarily very different—epubceck does attempt to enforce the spec—but "passes epubcheck" is easy to check, while "conforms to the spec" is not.

Existing successful deployments of EPUB need what works today to continue working tomorrow, and epubcheck seems to be the best proxy of that.

> I'd love an example of something where EPUBCheck and the spec disagree (except the major known one regarding spine order please). I don't think there are many examples.

I don't have one. I don't particularly expect many differences to arise, but I expect some. In order to improve interoperability, the plan includes writing a test suite and making clarifications. This should be expected to expose some incompatibilities and differences we were not previously aware of. When that happens, since we cannot check all the content and all the viewers out there, it seems more prudent to side with epubcheck a priori, even if we can make some well reasoned exceptions.

When we attempt to make potentially breaking changes to the web platform, companies with broad indexes of websites often make comments like "this change would break 0.5% of existing sites, which is too much, so we cannot do it". Existing EPUB content isn't online and indexed in the same way. Discovering whether changes are breaking will therefore be harder, but thanks to the pervasive use of epubcheck, we have a proxy.

Maybe that's the wrong way to go about it, but what I am trying to do here is to find a guideline that will help protect existing deployments, without relying on hyper-vigilance of actors in those markets.

**Comment by iherman** [comment]
@frivoal while I understand the roots of the proposal (some of those issues have been discussed in #19) what bothers me is that epubcheck is also a living entity. It is not, and should not be, frozen; it is continuously developed. In an ideal situation, it would co-develop with the evolution of EPUB 3.X, and this is envisaged in the liaison section of the standard (maybe this should be made stronger?). However, your proposal, that relies on a fixed version of epubcheck, makes such an evolution fairly difficult.

The discussion, as outlined in #19, is that if there are features that are defined in EPUB 3.2, used by some publishers, but not implemented, for whatever reasons, by reading systems (or are implemented only by one) could nevertheless be kept in the specification albeit as a non-normative feature. You have a better knowledge of the W3C process than I have, but I think we can both agree that this is possible per current process. Do you think that by making this aspect more explicit in the charter for the aforementioned cases would help to dissipate the concerns?

**Comment by murata2makoto** [comment]
@iherman @frivoal In ISO, I have heard of "reference implementation".  I have never seen it, but AFAIK, it is basically a normative annex.  If the rest of the spec is in conflict with the reference implementation, you cannot easily say that the reference implementation is broken but the spec is not.   In other words, conflicts between the reference implementation and the rest of the spec are treated just like those between Clause 2 and Clause 3.

I do not think that having a reference implementation hampers evolution.  We only have to make  prose and the reference implementation evolve together.

**Comment by iherman** [comment]
@murata2makoto I do not know whether the W3C process would accommodate with such a concept. Regardless, I do see two problems, though:

1. In general, W3C members have always pushed back against W3C, as such, developing some reference implementations, because they regard that as a competition to their own business. On the other hand, W3C is governed by a strict vendor neutrality, so picking such an implementation that is _not_ developed by W3C could be considered as a breach of that neutrality.
2. The ugly reality is that development of epubcheck needs money. The PBG has been absolutely great in finding some funding for the continuing work of epubcheck, but has been a tough thing to do (and the problems we are facing these days would not make it easier). Relying, in the WG work, on a development being so dependent on external funding may be a problem.

**Comment by iherman** [comment]
@frivoal, trying to close this issue (and the related issue #23)...

I continue to think that a dependency on epubcheck is not appropriate. Things would be in a reverse order:  the development of epubcheck _relies_ on the latest EPUB 3.2 document; in fact, it is much more stringent today than it was with EPUB 3.01. I believe that relationship should remain unchanged. 

However, your second proposed change clearly reflects a general concern, also expressed in #23. Your proposal said:

> There is an exception with any feature that is present in EPUB 3.2 and that do not have several known implementations in reading systems, but publications using this feature have a significant deployment. Such features must be kept when advancing to Proposed Recommendation but must be marked either as [deprecated](https://www.w3.org/publishing/epub32/epub-spec.html#deprecated) or non-normative. Documents using such features must not be made non-conformant to newer versions of the EPUB specification.

Let me propose something slightly different, namely:

> As an exception, features present in EPUB 3.2 may be kept when advancing to Proposed Recommendation even if there is no known multiple implementations in a reading systems, but significant document deployment, based on that feature, exist. Such features should either be marked as [deprecated](https://www.w3.org/publishing/epub32/epub-spec.html#deprecated)  or marked as non-normative. Documents using such features must not be made non-conformant to newer versions of the EPUB specification.

I believe this is perfectly in line with the process, any WG can choose to do this, but making it explicit might help to alleviate concerns.

@TzviyaSiegman @wareid @dauwhe @swickr ?

**Comment by murata2makoto** [comment]
I think that the idea of blessing epubcheck as a reference implementation should be discussed in the PBG.  It should not be easily turned down.

I do not agree on Ivan's two points.  Rather, I think that it might become a bit easier to solicit more funding if epubcheck becomes a reference implementation.  I recently learned that JPEG 2000 has a reference implementation, [OpenJPEG](http://www.openjpeg.org). 

As for Ivan's wording, I would like to replace "may be kept" by "must be kept".

**Comment by iherman** [comment]
> I do not agree on Ivan's two points.

I would like to understand what you do not agree with... those points are merely describing facts.

**Comment by murata2makoto** [comment]
@iherman 

>In general, W3C members have always pushed back against W3C, as such, developing some reference implementations, because they regard that as a competition to their own business. On the other hand, W3C is governed by a strict vendor neutrality, so picking such an implementation that is not developed by W3C could be considered as a breach of that neutrality.

Nobody is challenging epubcheck.  Everybody is using it.  It is very hard to imagine somebody is going to assume it as a challenge to their business.

> The ugly reality is that development of epubcheck needs money. The PBG has been absolutely great in finding some funding for the continuing work of epubcheck, but has been a tough thing to do (and the problems we are facing these days would not make it easier). Relying, in the WG work, on a development being so dependent on external funding may be a problem.

If we can say that epubcheck is a reference implementation, it might become a bit easier to solicit more funding.

**Comment by wareid** [comment]
I know it is a charter, but I am wary of statements like "must" considering we haven't explored anything yet, and I do not want to paint ourselves into an awkward corner. I prefer Ivan's wording. 

This is my first charter so I don't know if its common to do this, but I see these things as valid "implementations" of EPUB:
1. A tool that builds EPUB (i.e. InDesign, Sigil, Word2EPUB, etc.)
2. A valid EPUB file
3. An ingestion pipeline (specifically one that uses a validator or validators to process an EPUB file)
4. A Reading System/User Agent

Obviously EPUBCheck is really important to several of these implementations, but it's not an implementation itself. If anything, it's a key part of the test framework we'll be building once we enter that process. But it's also a community project funded by the publishing community, and not "owned" by anyone in particular. Including it as a reference implementation could have people look and say "Oh well, the W3C owns it now, why do I need to fund it." 

I personally am OK with outlining this in the specification if that helps others understand where we are looking for implementations/where they might fall in the ecosystem, but only if it's not in opposition to any process requirements.

**Comment by murata2makoto** [comment]
@wareid 
>I know it is a charter, but I am wary of statements like "must" considering we haven't explored anything yet, and I do not want to paint ourselves into an awkward corner. I prefer Ivan's wording.

I had very bad experiences with EPUB 3.1.  I tried to make it backward compatible with EPUB 3.0.1, but I failed to convince people.  It would have been nice if there was a charter which says that all exising EPUB publications must continue to be conformant.  This time, I would like to have a charter that guarantees features used by commercial publications must be kept.  I do not want to be in an awkward corner again.

**Comment by wareid** [comment]
I think we've included enough language in the charter in other places to guarantee, and I think Dave and I have gone on the record in multiple calls in support of, backwards compatibility. It benefits absolutely no one for us to produce a version of EPUB that is not compatible with previous versions. 

I completely understand the fears from EPUB 3.1, but I don't know how many more ways we can say "EPUB 3.x will be backwards compatible with previous versions of EPUB". Especially since EPUBs and the tools that create them are considered implementations of the specification, we really are eliminating the possibility of features getting dropped when there's implementations of them.

**Comment by murata2makoto** [comment]
EPUB 3.1 was said to be backwards compatible when it was being created.  I am thus still worried.

Here is my worry.  Application of the W3C process to the next version of EPUB might lead to removal of non-interoperable features, even if they are used by one implementation.  I thus would like the charter explicitly state that such non-interoperable features must be kept.  It might be better to ensure that no features of EPUB 3.2 will be dropped and no publications conforming to EPUB 3.2 will become non-conformant.

In the history of Japanese domestic character set standards, the fourth revision of JIS X 0208 is considered highly important.  From the beginning, it was clearly stated this revision does not add or remove any characters, does not change code positions, and does not change example glyph images.  During its development, it was found that some characters in the previous edition were introduced by mistake.  Most notably, https://en.wiktionary.org/wiki/妛 was introduced instead of https://ja.wiktionary.org/wiki/𡚴.  But 妛 has not and will not be removed from JIS X 0208, Unicode, and ISO/IEC 10646.

**Comment by iherman** [comment]
@frivoal, I think all the issues/questions have been discussed, and the charter proposal reflects consensus. In order to send the charter proposal to the AC vote (possibly next week), I would like to close this issue by this week end. Is that o.k.?

**Comment by frivoal** [comment]
I'm ok with closing, thanks for checking.
