### ISSUE TITLE
List the WHATWG in the Coordination section

### ISSUE THREAD

**Issue by frivoal** [w3c/epub-3-wg-charter#9]
The charter mentions HTML as a file format used in EPUB, and correctly links to the definition of HTML at the WHATWG. This is good.

It also says:
> Any properties or values that influence rendering inside viewports; these issues should be deferred to Working Groups defining rendering, like HTML, CSS, or SVG.

This is good too.

However, the WHATWG, which handles HTML is not listed in the Coordination section. It should be.

**Comment by iherman** [comment]
I agree. I will handle this in a separate PR (alongside the comment in https://github.com/w3c/epub-3-wg-charter/issues/10, which is similar), ie, if somebody opposes this, it can be discussed there.

<sub>[View in Slack](https://iherman.slack.com/archives/C011FD3ST52/p1586767729000300)</sub>

**Comment by dauwhe** [comment]
Fixed via #11
